import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

// Simple English to Hiligaynon Dictionary
const dictionary = {
  en: {
    dashboard: "Dashboard",
    reportIncident: "Report Incident",
    hotlines: "Hotlines",
    firstAid: "First Aid Guide",
    logout: "Log Out",
    welcome: "Welcome",
    emergencyType: "Emergency Type",
    location: "Location",
    description: "Description",
    submit: "Submit",
    pending: "Pending",
    inProgress: "In Progress",
    resolved: "Resolved",
    reports: "Your Reports",
    evacuation: "Evacuation Centers",
    household: "Household",
    profile: "Profile",
    notifications: "Notifications",
    instantSos: "Instant Emergency SOS",
    holdSos: "Hold 3 seconds to alert rescuers",
    activatingSos: "⚠️ ACTIVATING... KEEP HOLDING!",
    worksOffline: "Works offline via SMS",
    myReports: "My reports",
    activeAlerts: "Active alerts",
    announcements: "Announcements",
    viewAll: "View all",
    incidentType: "Incident Type *",
    selectType: "Select Incident Type",
    locationLabel: "Location / Specific Landmarks *",
    colExactLocation: "Exact Location",
    gpsLocationOnly: "Coordinates Only (Map)",
    locationPlaceholder: "Enter specific location (e.g. Purok 3 near chapel) or tap on map",
    descriptionLabel: "Description *",
    descriptionPlaceholder: "Describe the situation, required assistance, or immediate hazards...",
    uploadPhoto: "Upload Photo (Optional)",
    uploadDragBox: "Click or drag an image here to attach",
    floodSafety: "Flooding Safety Procedures",
    earthquakeSafety: "Earthquake: Duck, Cover, and Hold",
    kitEssentials: "Emergency Kit Essentials",
    firstAidGuide: "First Aid Guide",
    cprTitle: "Hands-Only CPR",
    chokingTitle: "Choking (Heimlich Maneuver)",
    bleedingTitle: "Severe Bleeding",
    burnsTitle: "Severe Burns",
    snakeTitle: "Snake Bite",
    addAnnouncement: "Add Announcement",
    loadingBulletins: "Loading bulletins...",
    noAnnouncements: "No announcements posted in this category.",
    by: "By",
    floodTip1: "Avoid walking or driving through floodwaters. Just 6 inches of moving water can knock you down.",
    floodTip2: "If floodwaters rise around your car, abandon the car immediately and move to higher ground.",
    floodTip3: "Disconnect electrical appliances and turn off gas lines if flooding is imminent in your household.",
    floodTip4: "Keep emergency bags ready containing clean water, medicine, dry food, and powerbanks.",
    eqTip1: "DUCK down onto your hands and knees.",
    eqTip2: "COVER your head and neck under a sturdy table or desk.",
    eqTip3: "HOLD ON to your shelter until the shaking stops.",
    eqTip4: "Stay away from glass windows, heavy light fixtures, and brick walls.",
    kitDesc: "Maintain a go-bag containing: Bottled water (3-day supply), canned goods, first-aid kit, flashlight, batteries, whistle (to signal for help), local barangay rescue contacts, and matchsticks.",
    firstAidDesc: "Follow these critical steps while waiting for responders to arrive.",
    firstAidWarn: "If unsure, do not move the patient.",
    cpr1: "Check for responsiveness: Tap the shoulder and shout, 'Are you OK?'",
    cpr2: "Call for help: Ensure an emergency report has been submitted.",
    cpr3: "Push hard and fast: Place the heel of one hand in the center of the chest. Put your other hand on top and interlace your fingers.",
    cpr4: "Push down at least 2 inches at a rate of 100 to 120 pushes a minute.",
    cpr5: "Don't stop: Continue until responders arrive or the person starts breathing.",
    choking1: "Stand behind the person and wrap your arms around their waist.",
    choking2: "Make a fist with one hand and place it just above the person's navel (belly button).",
    choking3: "Grab your fist with your other hand.",
    choking4: "Make a quick, upward thrust into the stomach.",
    choking5: "Repeat until the object is dislodged and they can breathe.",
    bleeding1: "Apply direct pressure: Use a clean cloth, towel, or shirt and press firmly directly on the wound.",
    bleeding2: "Do not remove the cloth: If blood soaks through, add another cloth on top. Never lift the first cloth off.",
    bleeding3: "Elevate: If the wound is on an arm or leg, raise it above the level of the heart if possible.",
    bleeding4: "Keep pressure: Maintain continuous hard pressure until responders take over.",
    burns1: "Stop the burning: Remove the person from the heat source. If clothing is on fire, have them stop, drop, and roll.",
    burns2: "Cool the burn: Run cool (not cold or freezing) water over the burn for 10-15 minutes.",
    burns3: "Remove tight items: Quickly remove rings or tight clothing from the burned area before it swells.",
    burns4: "Do NOT pop blisters: Cover the burn loosely with a sterile, non-stick bandage or clean cloth.",
    burns5: "Do NOT apply ice, butter, or ointments to a severe burn.",
    snake1: "Stay calm and still: Movement causes venom to spread faster. Keep the patient calm.",
    snake2: "Keep the bite below heart level: Position the bitten area lower than the heart.",
    snake3: "Remove jewelry/tight clothing: Remove items near the bite before swelling begins.",
    snake4: "Do NOT cut the wound or try to suck out venom.",
    snake5: "Do NOT apply a tourniquet or ice.",
    snake6: "Wait for the ambulance. If you saw the snake, remember its color/shape but do not try to catch it.",
    youAreHere: "📍 You are here",
    noRoute: "Cannot draw route: Your location is unavailable. Please enable GPS permissions for this site.",
    gpsDisabled: "GPS disabled. Using a simulated location for demo purposes.",
    geoNotSupported: "Geolocation not supported. Using a simulated location.",
    status: "Status",
    occupancy: "Occupancy",
    capacity: "Capacity",
    evacuationCenters: "Evacuation Centers",
    newCenter: "New Center",
    loadingCenters: "Loading evacuation centers...",
    noCenters: "No evacuation centers found.",
    adminTip: "Admin Tip: Click anywhere on the map to capture coordinates directly for the latitude/longitude fields.",
    editShelter: "✏️ Edit Shelter",
    registerShelter: "⛺ Register Shelter",
    centerName: "Center Name *",
    locationAddress: "Location Address *",
    maxCapacity: "Max Capacity *",
    currentHeadcount: "Current Occupants Headcount",
    latitude: "Latitude",
    longitude: "Longitude",
    saveUpdates: "Save Updates",
    addShelter: "Add Shelter",
    statusOpen: "Open",
    statusFull: "Full",
    statusClosed: "Closed",
    capacityOccupancy: "Capacity Occupancy",
    lguAdvisory: "LGU Advisory: Shelters operate on a first-come, first-served basis. If a center is marked as Full, please locate the next nearest open center on the map or contact MDRRMO.",
    loadingHotlines: "Loading hotlines directory...",
    municipalResponders: "Municipal Responders & LGU Hotlines",
    barangayDesks: "Barangay Tanod & Community Desk Numbers",
    noBarangayDesks: "No Barangay-specific contact desks registered in the system yet.",
    call: "Call",
    loadingDetails: "Loading details...",
    reportNotFound: "Incident report not found.",
    backToList: "Back to list",
    printReport: "Print Report",
    reportId: "Report ID",
    inBarangay: "in Barangay",
    statusTimeline: "Status Timeline",
    updateStatus: "Update Status",
    newStatus: "New Status",
    comment: "Comment",
    commentPlaceholder: "Provide details about updates...",
    updating: "Updating...",
    logStatusUpdate: "Log Status Update",
    locationRoute: "Location & Route Tracking",
    liveTrackingAssigned: "Live tracking assigned responder:",
    waitingDispatch: "Waiting for responder dispatch assignment...",
    isEnRoute: "is en route to your location.",
    liveTracking: "LIVE TRACKING",
    reporterProfile: "Reporter Profile & Medical Flags",
    reporter: "Reporter:",
    rescuerInfo: "RESCUER INFORMATION FLAGS",
    bloodType: "Blood Type:",
    unknown: "Unknown",
    allergies: "Allergies:",
    noneReported: "None reported",
    conditions: "Conditions / Disabilities:",
    disabilitiesNone: "Disabilities/Conditions: None reported",
    nextOfKin: "Next of Kin / Contact:",
    name: "Name:",
    phone: "Phone:",
    householdMembersList: "Household Members",
    listed: "listed",
    noHouseholdDeclared: "No household members declared.",
    yrs: "yrs",
    medNeeds: "Med/Needs:",
    loadingHousehold: "Loading household data...",
    householdHeadcount: "Household Headcount",
    memberSingle: "member",
    memberPlural: "members",
    noHouseholdListed: "No household members listed yet",
    householdInfo: "Add members of your family or roommates who reside in your home to keep disaster responders informed.",
    yrsOld: "yrs old",
    medicalNotesLabel: "Medical Notes / Special Needs",
    medicalVal: "Medical:",
    noMedicalVal: "No pre-existing medical conditions listed.",
    addFamilyMember: "Add Family Member",
    fullName: "Full Name *",
    enterCompleteName: "Enter complete name",
    ageStar: "Age *",
    ageLabel: "Age",
    genderStar: "Gender *",
    selectLabel: "Select --",
    male: "Male",
    female: "Female",
    other: "Other",
    medicalPlaceholder: "e.g. Asthma, wheelchair-bound, needs maintenance meds, infant formula, etc. (leave blank if none)",
    addingLabel: "Adding...",
    addMemberBtn: "Add Member",
    disasterTip: "Disaster Preparedness Tip: Ensure that elderly relatives and young children are noted with special needs. This information assists the LGU in organizing priority transport during flash floods or evacuations.",
    notificationsInbox: "Notifications Inbox",
    notificationsDesc: "View and manage alerts sent to your profile",
    markAllRead: "Mark all read",
    loadingNotifications: "Loading notifications...",
    noNotifications: "No notifications yet.",
    profileDetails: "Profile Details",
    usernameLabel: "Username",
    passwordLabel: "Password",
    fullNameLabel: "Full Name",
    phoneNumberLabel: "Phone Number",
    barangayLabel: "Barangay",
    purokSitioLabel: "Purok / Sitio",
    purokSitioPlaceholder: "e.g. Purok 3 / Sitio Mahayag",
    medicalInfoHeading: "Medical Information (Critical for Rescue headcounts)",
    bloodTypeLabel: "Blood Type",
    unknownSelect: "Unknown / Select --",
    allergiesLabel: "Allergies",
    allergiesPlaceholder: "List food, drug, or environmental allergies (or type 'None')",
    medicalConditionsLabel: "Medical Conditions",
    medicalConditionsPlaceholder: "Asthma, hypertension, diabetes, physical disabilities, etc. (critical for evacuation coordinators)",
    emergencyContactHeading: "Emergency Next of Kin Contact",
    contactNameLabel: "Contact Name",
    contactNamePlaceholder: "Emergency contact full name",
    contactPhoneLabel: "Contact Phone",
    contactPhonePlaceholder: "e.g. 09170001111",
    savingDetails: "Saving Details...",
    saveEmergencyProfile: "Save Emergency Profile",
    securitySettings: "Security Settings",
    currentPasswordLabel: "Current Password",
    newPasswordLabel: "New Password",
    updatePasswordLabel: "Update Password",
    settingsTitle: "Settings",
    settingsDesc: "Configure your platform preferences",
    notificationSettings: "Notification Settings",
    emailAdvisories: "Email Emergency Advisories",
    emailAdvisoriesDesc: "Receive real-time public advisories on your registered email address.",
    smsAdvisories: "SMS Emergency Advisories",
    smsAdvisoriesDesc: "Receive critical weather warnings and evacuation notices via text message (SMS).",
    darkTheme: "Dark Theme Interface",
    darkThemeDesc: "Switch the application theme color scheme to high-contrast dark mode.",
    fillAllFields: "Please fill in all fields.",
    invalidLogin: "Invalid username or password. Please try again.",
    emergencyResponse: "Emergency Response",
    communityPlatform: "Community Platform",
    signInToContinue: "Sign in to continue",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    contactAdmin: "Please contact the Municipality IT administrator to reset your password.",
    loggingIn: "Logging in...",
    loginBtn: "Login",
    noAccount: "Don't have an account?",
    registerHere: "Register here",
    legalWarningReq: "You must agree to the Legal Warning and Data Privacy terms.",
    passwordTooWeak: "Password is too weak. Must contain at least a capital letter, a number, and a symbol.",
    phoneMustBe11: "Phone number must be exactly 11 digits starting with 09.",
    passwordsDoNotMatch: "Passwords do not match. Please try again.",
    mustBe18: "You must be at least 18 years old to register. Minors should ask a parent or guardian to report for them.",
    uploadValidId: "Please upload a valid ID photo.",
    captureSelfie: "Please capture a live selfie to verify your identity.",
    checkingGps: "Checking GPS location boundary...",
    registrationBlocked: "Registration Blocked: Your GPS location is outside the Jamindan/Capiz region. Only local residents are allowed to register.",
    verifyingIdentity: "Verifying identity...",
    accountRegistered: "Registration successful! You will receive an email (check Spam folder) once your account is verified by an Admin.",
    registrationFailed: "Registration failed. Check your connection or try a different username.",
    residentRegistration: "Resident Registration",
    emergencyPlatform: "Emergency Response Platform",
    ageReqWarning: "Age Requirement: You must be 18 years or older to register. An Administrator will review your submitted ID and Selfie before activating your account to prevent false reports.",
    createUsername: "Create a username",
    createStrongPass: "Create a strong password",
    confirmPassword: "Confirm Password",
    retypePass: "Re-type password",
    completeName: "Complete name",
    agePlus: "18+",
    phoneEg: "e.g. 09171234567",
    selectBarangay: "-- Select Barangay --",
    identityVerification: "Identity Verification",
    typeOfId: "Type of Valid ID",
    selectIdType: "-- Select ID Type --",
    uploadId: "Upload {idType} (Showing Date of Birth)",
    liveSelfieVerif: "Live Selfie Verification",
    openCamera: "Open Camera to Take Selfie",
    capturePhoto: "Capture Photo",
    cancelBtn: "Cancel",
    retakeSelfieBtn: "Retake Selfie",
    legalWarningText: "Legal Warning: I understand that submitting fake emergency reports is a crime punishable by law under the Anti-Prank Caller Act. I also consent to the collection of my personal data under the Data Privacy Act.",
    submittingReg: "Submitting Registration...",
    submitRegBtn: "Submit Registration for Review",
    alreadyRegistered: "Already registered?",
    logInLink: "Log In",
    loadingCommandCenter: "Loading Command Center...",
    commandCenter: "Command Center",
    responderActive: "Responder Active",
    welcomePrefix: "Welcome,",
    activeDispatch: "Active Dispatch",
    noActiveEmergencies: "No active emergencies at this time.",
    respondToAlert: "Respond to Alert",
    viewAllIncidents: "View All Incidents",
    pendingStatus: "Pending",
    enRoute: "En Route",
    resolvedToday: "Resolved Today",
    respondersCount: "Responders",
    systemOverview: "System Overview",
    totalLifetimeReports: "Total Lifetime Reports",
    sinceLaunch: "Since platform launch",
    noReportsExport: "No incident reports found to export.",
    confirmDeleteReport: "Are you sure you want to permanently delete incident report {code}? This action cannot be undone.",
    failedDeleteReport: "Failed to delete report.",
    republicOfPh: "Republic of the Philippines",
    provinceOfCapiz: "Province of Capiz",
    municipalityJamindan: "Municipality of Jamindan",
    officeMdrrmo: "OFFICE OF DISASTER RISK REDUCTION AND MANAGEMENT (MDRRMO)",
    officialRegistryReport: "Official Incident Registry Report",
    generatedOn: "Generated on:",
    roleLabel: "Role:",
    statusFilterLabel: "Status Filter:",
    allStatuses: "All Statuses",
    typeFilterLabel: "Type Filter:",
    allTypes: "All Types",
    searchTermLabel: "Search term:",
    countRecords: "Count: {count} record(s)",
    submitNewReport: "Submit New Report",
    exportCsv: "Export as CSV",
    exportPdf: "Export PDF Report",
    searchPlaceholder: "Search code, name, barangay...",
    filterByStatus: "Filter by Status",
    filterByType: "Filter by Type",
    fetchingRecords: "Fetching incident records...",
    noReportsMatching: "No reports found matching the filters.",
    colCode: "Report Code",
    colPriority: "Priority",
    colType: "Type",
    colDesc: "Description",
    colReporter: "Reporter",
    colBarangay: "Barangay",
    colDate: "Submitted Date",
    colStatus: "Status",
    colAction: "Action",
    badgeCritical: "CRITICAL",
    badgeNormal: "Normal",
    language: "Language",
    pushNotifications: "Push Notifications",
    enabled: "Enabled",
    disabled: "Disabled",
    darkMode: "Dark Mode",
    currentlyOn: "Currently On",
    currentlyOff: "Currently Off",
    accountSecurity: "Account & Security",
    accountSecurityDesc: "Update profile or password",
    myProfile: "My Profile",
    householdList: "Household List",
    emergencyHotlines: "Emergency Hotlines",
    newsUpdates: "News & Updates",
    emergencyTips: "Emergency Tips",
    navHome: "Home",
    navReport: "Report",
    navDispatch: "Dispatch",
    navStatus: "Status",
    navVerify: "Verify",
    navTeammates: "Teammates",
    navMap: "Map",
    navMore: "More",
    searchHotlines: "Search hotlines by name, barangay, or number...",
    recentlyCalled: "Recently Called"
  },
  hil: {
    dashboard: "Dasbord",
    reportIncident: "I-report ang Insidente",
    hotlines: "Mga Hotline",
    firstAid: "Giya sa First Aid",
    logout: "Mag-logout",
    welcome: "Maayong Pag-abot",
    emergencyType: "Klase sang Emerhensya",
    location: "Lugar",
    description: "Pagsaysay",
    submit: "Ipadala",
    pending: "Ginahulat",
    inProgress: "Ginaproseso",
    resolved: "Nasolbar",
    reports: "Mga Report Mo",
    evacuation: "Evacuation Center",
    household: "Miyembro sang Panimalay",
    profile: "Imo Profile",
    notifications: "Mga Notipikasyon",
    instantSos: "Dalalian nga SOS",
    holdSos: "Pinduta sing 3 ka segundo",
    activatingSos: "⚠️ GINAPADALA... PADAYUNA ANG PAGPINDUT!",
    worksOffline: "Nagagana offline paagi sa SMS",
    myReports: "Akong Mga Report",
    activeAlerts: "Mga Aktibo nga Alerto",
    announcements: "Mga Pahibalo",
    viewAll: "Tan-awa Tanan",
    incidentType: "Klase sang Emerhensya *",
    selectType: "Magpili sang Klase",
    locationLabel: "Lugar / Marka sang Lugar *",
    locationPlaceholder: "Ibutang ang eksakto nga lugar (hal. Purok 3 lapit sa kapilya) o pinduta sa mapa",
    descriptionLabel: "Pagsaysay *",
    descriptionPlaceholder: "I-istorya ang sitwasyon, kinahanglan nga bulig, o peligro...",
    uploadPhoto: "Mag-upload sang Litrato (Opsyonal)",
    uploadDragBox: "Pinduta o i-drag ang litrato diri",
    floodSafety: "Mga Pagsulundan sa Pagbaha",
    earthquakeSafety: "Linog: Duko, Panago, kag Kapot",
    kitEssentials: "Mga Kinahanglanon sa Emergency Kit",
    firstAidGuide: "Giya sa First Aid",
    cprTitle: "CPR (Kamot Lamang)",
    chokingTitle: "Natuok (Heimlich Maneuver)",
    bleedingTitle: "Daku nga Pagdugo",
    burnsTitle: "Malubha nga Paso",
    snakeTitle: "Kagat sang Man-ug",
    addAnnouncement: "Magdugang Pahibalo",
    loadingBulletins: "Ginakarga ang mga balita...",
    noAnnouncements: "Wala sing pahibalo sa sini nga kategorya.",
    by: "Halin kay",
    floodTip1: "Likawi ang maglakaw o magmaneho sa baha. Ang 6 pulgada nga tubig makatumba sa imo.",
    floodTip2: "Kung magsaka ang baha palibot sa imo salakyan, bayaan dayon ang salakyan kag magkadto sa mataas nga lugar.",
    floodTip3: "Huksa ang mga appliances kag patya ang gas kung may nagahilapit nga baha sa inyo balay.",
    floodTip4: "I-preparar ang mga emergency bags nga may limpyo nga tubig, bulong, uga nga pagkaon, kag powerbanks.",
    eqTip1: "DUKO sa imo mga kamot kag tuhod.",
    eqTip2: "PANAGO kag tabuni ang imo ulo kag liog sa idalom sang malig-on nga lamesa.",
    eqTip3: "KAPOT sa imo ginapanaguan asta nga mag-untat ang linog.",
    eqTip4: "Maglayo sa mga bintana nga salamin, mabug-at nga suga, kag pader.",
    kitDesc: "Mag-preparar sang go-bag nga may: Tubig (para sa 3 ka adlaw), delata, first-aid kit, flashlight, baterya, pito (para mangayo bulig), numero sang barangay rescue, kag posporo.",
    firstAidDesc: "Sunda ining mga importante nga tikang samtang nagahulat sa mga responder.",
    firstAidWarn: "Kung indi ka sigurado, indi pag-ihulag ang pasyente.",
    cpr1: "Tseka kung naga-responde: Taptapa ang abaga kag magsiyagit, 'Okay ka lang?'",
    cpr2: "Mangayo bulig: Siguraduha nga may nakapadala sang report sang emerhensya.",
    cpr3: "Iduso sing mabaskog kag madasig: Ibutang ang palad sang isa ka kamot sa tunga sang dughan. Ibutang ang isa pa ka kamot sa ibabaw kag ilakip ang imo mga tudlo.",
    cpr4: "Iduso panubo sang 2 ka pulgada sing 100-120 ka beses kada minuto.",
    cpr5: "Indi mag-untat: Padayuna asta mag-abot ang mga responder o mag-ginhawa na ang pasyente.",
    choking1: "Tindog sa likod sang tawo kag ihakus ang imo mga butkon sa iya hawak.",
    choking2: "Kumo-a ang isa ka kamot kag ibutang sa ibabaw lang sang iya pusod.",
    choking3: "Kapti ang imo kumo sang imo isa ka kamot.",
    choking4: "Iduso sing madasig kag pasaka pasulod sa iya tiyan.",
    choking5: "Uli-uliha asta nga maggua ang nakabara kag maka-ginhawa siya.",
    bleeding1: "Pugngi ang samad: Gamit sang limpyo nga trapo ukon bayo, idu-on sing mabaskog sa samad.",
    bleeding2: "Indi pag-kuhaa ang trapo: Kung maglapos ang dugo, patungi lang sang isa pa. Indi gid pag-alsahon ang una nga trapo.",
    bleeding3: "I-alsa: Kung ang samad yara sa butkon o tiil, i-alsa ini mas mataas sa kasing-kasing kung pwede.",
    bleeding4: "Padayuna ang pagdu-on: Ipadayon ang pagdu-on asta mag-abot ang mga responder.",
    burns1: "Untata ang pagkasunog: Ipalayo ang tawo sa kalayo. Kung nagadabadaba ang bayo, pahigdaa kag paligira siya.",
    burns2: "Pabugnawa ang paso: Padalagan ang bugnaw (indi tuman ka bugnaw o may yelo) nga tubig sa paso sulod sang 10-15 ka minuto.",
    burns3: "Huksa ang mga nagahugot: Dalidali nga hukson ang mga singsing o hugot nga bayo sa paso nga parte bag-o maghubag.",
    burns4: "INDI pag-buslutan ang mga lapalapa (blisters): Tabuni ang paso sang limpyo nga gasa o trapo.",
    burns5: "INDI pagbutangi sang yelo, mantikilya, o ointment ang malubha nga paso.",
    snake1: "Magpakalma kag indi maggiho: Ang paggiho nagapasanyog sang paglapta sang dalit. Pakalmahon ang pasyente.",
    snake2: "Ibutang ang kagat sa idalom sang kasingkasing.",
    snake3: "Huksa ang mga alahas/hugot nga bayo lapit sa kagat bag-o maghubag.",
    snake4: "INDI pag-hiwaa ang samad o sopsopon ang dalit.",
    snake5: "INDI pagbutangan sang tourniquet o yelo.",
    snake6: "Hulata ang ambulansya. Kung nakita mo ang man-ug, tandai ang kolor/itsura pero indi pagdakpa.",
    youAreHere: "📍 Ari ka diri",
    noRoute: "Indi mapakita ang ruta: Wala ang imo lokasyon. Palihog i-on ang GPS permissions para sini.",
    gpsDisabled: "Napatay ang GPS. Ginagamit ang simulated nga lokasyon para sa demo.",
    geoNotSupported: "Wala suporta sa Geolocation. Ginagamit ang simulated nga lokasyon.",
    status: "Estado",
    occupancy: "Kadamuon sang Tawo",
    capacity: "Kapasidad",
    evacuationCenters: "Evacuation Centers",
    newCenter: "Bag-o nga Center",
    loadingCenters: "Ginakarga ang mga evacuation center...",
    noCenters: "Wala sing evacuation center nga nakita.",
    adminTip: "Tip sa Admin: Pinduta bisan diin sa mapa para makuha ang coordinates para sa latitude/longitude.",
    editShelter: "✏️ I-edit ang Shelter",
    registerShelter: "⛺ I-rehistro ang Shelter",
    centerName: "Ngalan sang Center *",
    locationAddress: "Lugar sang Address *",
    maxCapacity: "Pinakadaku nga Kapasidad *",
    currentHeadcount: "Karon nga Kadamuon sang Tawo",
    latitude: "Latitude",
    longitude: "Longitude",
    saveUpdates: "I-save ang mga Pagbag-o",
    addShelter: "Idugang ang Shelter",
    statusOpen: "Bukas",
    statusFull: "Puno",
    statusClosed: "Sira",
    capacityOccupancy: "Kapasidad kag Kadamuon",
    lguAdvisory: "Pahibalo sang LGU: Ang mga shelter naga-operate suno sa 'first-come, first-served'. Kung 'Puno' na ang center, palihog pangita sang iban nga bukas nga center sa mapa ukon kontaka ang MDRRMO.",
    loadingHotlines: "Ginakarga ang listahan sang mga hotline...",
    municipalResponders: "Municipal Responders kag LGU Hotlines",
    barangayDesks: "Barangay Tanod kag Community Desk",
    noBarangayDesks: "Wala pa sang Barangay contact desk nga narehistro sa sistema.",
    call: "Tawag",
    loadingDetails: "Ginakarga ang mga detalye...",
    reportNotFound: "Wala makita ang incident report.",
    backToList: "Mabalik sa listahan",
    printReport: "I-print ang Report",
    reportId: "Report ID",
    inBarangay: "sa Barangay",
    statusTimeline: "Timeline sang Estado",
    updateStatus: "I-update ang Estado",
    newStatus: "Bag-o nga Estado",
    comment: "Komentaryo",
    commentPlaceholder: "Maghatag sing detalye parte sa pag-update...",
    updating: "Gina-update...",
    logStatusUpdate: "I-save ang Pag-update",
    locationRoute: "Lokasyon kag Ruta",
    liveTrackingAssigned: "Live tracking nga responder:",
    waitingDispatch: "Nagahulat sang responder dispatch...",
    isEnRoute: "nagalakat pakadto sa imo lokasyon.",
    liveTracking: "LIVE TRACKING",
    reporterProfile: "Profile sang Nag-report kag Medical Flags",
    reporter: "Nag-report:",
    rescuerInfo: "RESCUER INFORMATION FLAGS",
    bloodType: "Blood Type:",
    unknown: "Wala nabal-an",
    allergies: "Allergies:",
    noneReported: "Wala nareport",
    conditions: "Kondisyon / Kasablagan:",
    disabilitiesNone: "Kasablagan/Kondisyon: Wala nareport",
    nextOfKin: "Nakahibalo / Kontakon:",
    name: "Ngalan:",
    phone: "Telepono:",
    householdMembersList: "Miyembro sang Panimalay",
    listed: "nga nakalista",
    noHouseholdDeclared: "Wala sang gin-declare nga miyembro sang panimalay.",
    yrs: "tuig",
    medNeeds: "Bulong/Kinahanglanon:",
    loadingHousehold: "Ginakarga ang datos sang panimalay...",
    householdHeadcount: "Kadamuon sang Panimalay",
    memberSingle: "miyembro",
    memberPlural: "ka miyembro",
    noHouseholdListed: "Wala pa sing nalista nga miyembro sang panimalay",
    householdInfo: "Idugang ang imo pamilya o mga kaupod sa balay para mahibal-an sang mga responder panahon sang kalamidad.",
    yrsOld: "tuig",
    medicalNotesLabel: "Medical Notes / Pinasahi nga Kinahanglanon",
    medicalVal: "Medikal:",
    noMedicalVal: "Wala sing nalista nga sakit.",
    addFamilyMember: "Idugang sa Pamilya",
    fullName: "Bilog nga Ngalan *",
    enterCompleteName: "Ibutang ang bilog nga ngalan",
    ageStar: "Edad *",
    ageLabel: "Edad",
    genderStar: "Kasarian *",
    selectLabel: "Pili-a --",
    male: "Lalaki",
    female: "Babayi",
    other: "Iban",
    medicalPlaceholder: "hal. Asthma, naka-wheelchair, kinahanglan maintenance, gatas sang lapsag, kag iban pa (pabay-an nga blangko kung wala)",
    addingLabel: "Ginadugang...",
    addMemberBtn: "Idugang ang Miyembro",
    disasterTip: "Tip sa Pagpanghanda: Siguraduhon nga ang mga tigulang kag kabataan may nakabutang nga pinasahi nga kinahanglanon. Makabulig ini sa LGU para unahon sila sa pag-evacuate kung may baha o kalamidad.",
    notificationsInbox: "Inbox sang mga Notipikasyon",
    notificationsDesc: "Tan-awa kag i-manage ang mga alerto nga ginpadala sa imo",
    markAllRead: "Markahan nga nabasa na",
    loadingNotifications: "Ginakarga ang mga notipikasyon...",
    noNotifications: "Wala pa sing notipikasyon.",
    profileDetails: "Mga Detalye sang Profile",
    usernameLabel: "Username",
    fullNameLabel: "Bilog nga Ngalan",
    phoneNumberLabel: "Numero sang Telepono",
    barangayLabel: "Barangay",
    purokSitioLabel: "Purok / Sitio",
    purokSitioPlaceholder: "hal. Purok 3 / Sitio Mahayag",
    medicalInfoHeading: "Impormasyon Medikal (Kinahanglan para sa Rescue)",
    bloodTypeLabel: "Blood Type",
    unknownSelect: "Wala nabal-an / Pili-a --",
    allergiesLabel: "Allergies",
    allergiesPlaceholder: "Ilista ang mga allergy sa pagkaon, bulong, o palibot (o ibutang 'Wala')",
    medicalConditionsLabel: "Medikal nga Kondisyon",
    medicalConditionsPlaceholder: "Asthma, highblood, diabetes, kasablagan, kag iban pa (importante para sa mga nagapang-evacuate)",
    emergencyContactHeading: "Tawo nga Kontakon Tion sang Emerhensya",
    contactNameLabel: "Ngalan sang Kontakon",
    contactNamePlaceholder: "Bilog nga ngalan sang kontakon",
    contactPhoneLabel: "Numero sang Kontakon",
    contactPhonePlaceholder: "hal. 09170001111",
    savingDetails: "Ginasave ang mga Detalye...",
    saveEmergencyProfile: "I-save ang Emergency Profile",
    securitySettings: "Settings sang Seguridad",
    currentPasswordLabel: "Karon nga Password",
    newPasswordLabel: "Bag-o nga Password",
    updatePasswordLabel: "I-update ang Password",
    settingsTitle: "Mga Settings",
    settingsDesc: "I-set ang imo paborito nga timplada sa platform",
    notificationSettings: "Settings sang Notipikasyon",
    emailAdvisories: "Mga Abiso sa Email",
    emailAdvisoriesDesc: "Magbaton sang live nga mga abiso sa imo rehistrado nga email.",
    smsAdvisories: "Mga Abiso sa SMS",
    smsAdvisoriesDesc: "Magbaton sang importante nga paandam sa tyempo kag evacuation sa text (SMS).",
    darkTheme: "Dark Theme",
    darkThemeDesc: "Ibaylo ang kolor sang aplikasyon sa madulom nga theme para indi masakit sa mata.",
    fillAllFields: "Palihog sulati ang tanan nga blanko.",
    invalidLogin: "Sala nga username o password. Palihog sulayi liwat.",
    emergencyResponse: "Pagsabat sa Emerhensya",
    communityPlatform: "Platform sang Komunidad",
    signInToContinue: "Mag-sign in para magpadayon",
    rememberMe: "Tandai ako",
    forgotPassword: "Nalimtan ang password?",
    contactAdmin: "Palihog kontaka ang IT admin sang Munisipyo para ma-reset ang password.",
    loggingIn: "Naga-login...",
    loginBtn: "Login",
    noAccount: "Wala pa sang account?",
    registerHere: "Mag-register diri",
    legalWarningReq: "Dapat ka magpasugot sa Legal Warning kag Data Privacy.",
    passwordTooWeak: "Mahuyang ang password. Dapat may capital letter, numero, kag simbolo.",
    phoneMustBe11: "Ang numero sang cellphone dapat 11 ka digits kag naga-umpisa sa 09.",
    passwordsDoNotMatch: "Wala nagasanto ang mga password. Palihog sulayi liwat.",
    mustBe18: "Dapat 18 ka tuig pataas ka para maka-rehistro. Ang mga minor de edad dapat magpabulig sa ginikanan.",
    uploadValidId: "Palihog i-upload ang imo valid ID.",
    captureSelfie: "Palihog mag-take sang selfie para ma-verify ang imo identity.",
    checkingGps: "Ginasiguro ang imo GPS location...",
    registrationBlocked: "Naharang: Ang imo GPS wala sa Jamindan/Capiz. Para lamang sa mga residente ang registration.",
    verifyingIdentity: "Gina-verify ang imo identity...",
    accountRegistered: "Madinalag-on nga naka-rehistro! Makabaton ka sang email (i-check ang imo Spam folder) kung ma-verify na sang Admin ang imo account.",
    registrationFailed: "Wala nagmadinalag-on. I-check ang imo connection ukon maggamit sang iban nga username.",
    residentRegistration: "Rehistrasyon sang Residente",
    emergencyPlatform: "Platform para sa Emerhensya",
    ageReqWarning: "Limitasyon sa Edad: Dapat 18 ka tuig pataas ka para maka-rehistro. I-review sang Admin ang imo ID kag Selfie antis i-activate ang account para malikawan ang fake nga report.",
    createUsername: "Maghimo sang username",
    createStrongPass: "Maghimo sang mabakod nga password",
    confirmPassword: "Kumpirmahon ang Password",
    retypePass: "I-type liwat ang password",
    completeName: "Bilog nga ngalan",
    agePlus: "18+",
    phoneEg: "hal. 09171234567",
    selectBarangay: "-- Pili-a ang Barangay --",
    identityVerification: "Pag-verify sang Identity",
    typeOfId: "Klase sang Valid ID",
    selectIdType: "-- Pili-a ang Klase sang ID --",
    uploadId: "I-upload ang {idType} (Napakita ang Adlaw sang Pagkatawo)",
    liveSelfieVerif: "Live nga Selfie Verification",
    openCamera: "Abrehan ang Camera para mag-Selfie",
    capturePhoto: "Pinduton para mag-Photo",
    cancelBtn: "I-cancel",
    retakeSelfieBtn: "Mag-Selfie Liwat",
    legalWarningText: "Legal Warning: Nakahangop ako nga ang maghatag sang fake nga report isa ka krimen base sa Anti-Prank Caller Act. Nagapasugot man ako nga i-kolekta ang akon personal nga datos base sa Data Privacy Act.",
    submittingReg: "Ginasumite ang Rehistro...",
    submitRegBtn: "I-sumite ang Rehistro para Ma-review",
    alreadyRegistered: "May account na?",
    logInLink: "Mag-Log In",
    loadingCommandCenter: "Ginakarga ang Command Center...",
    commandCenter: "Command Center",
    responderActive: "Aktibo nga Responder",
    welcomePrefix: "Maayong pag-abot,",
    activeDispatch: "Mga Gina-respondihan",
    noActiveEmergencies: "Wala sing aktibo nga emerhensya subong.",
    respondToAlert: "Respondihan ang Alerto",
    viewAllIncidents: "Tan-awa Tanan nga Insidente",
    pendingStatus: "Wala pa Maaksyunan",
    enRoute: "Nagapadulong Na",
    resolvedToday: "Nasolbar Subong",
    respondersCount: "Mga Responder",
    systemOverview: "Kabilugan sang Sistema",
    totalLifetimeReports: "Kabilugan nga mga Report",
    sinceLaunch: "Halin sang pag-umpisa",
    noReportsExport: "Wala sang makita nga report para ma-export.",
    confirmDeleteReport: "Sigurado ka nga permanenteng dulaon ang report nga {code}? Indi na ini mabalik.",
    failedDeleteReport: "Wala madula ang report.",
    republicOfPh: "Republika sang Pilipinas",
    provinceOfCapiz: "Probinsya sang Capiz",
    municipalityJamindan: "Munisipalidad sang Jamindan",
    officeMdrrmo: "OFFICE OF DISASTER RISK REDUCTION AND MANAGEMENT (MDRRMO)",
    officialRegistryReport: "Opisyal nga Report sang mga Insidente",
    generatedOn: "Hinimo sang:",
    roleLabel: "Koneksyon:",
    statusFilterLabel: "Filter sa Status:",
    allStatuses: "Tanan nga Status",
    typeFilterLabel: "Filter sa Klase:",
    allTypes: "Tanan nga Klase",
    searchTermLabel: "Ginpangita:",
    countRecords: "Kadamuon: {count} ka record",
    submitNewReport: "Magsumite sang Bag-o nga Report",
    exportCsv: "I-export sa CSV",
    exportPdf: "I-export sa PDF",
    searchPlaceholder: "Pangitaa ang code, ngalan, barangay...",
    filterByStatus: "I-filter sa Status",
    filterByType: "I-filter sa Klase",
    fetchingRecords: "Ginakuha ang mga rekord...",
    noReportsMatching: "Wala sang report nga nagasanto sa imo ginpangita.",
    colCode: "Code sang Report",
    colExactLocation: "Eksakto nga Lokasyon",
    gpsLocationOnly: "Coordinates Gikan sa Map",
    colPriority: "Prayoridad",
    colType: "Klase",
    colDesc: "Deskripsyon",
    colReporter: "Ang Nag-report",
    colBarangay: "Barangay",
    colDate: "Adlaw Ginhimo",
    colStatus: "Status",
    colAction: "Aksyon",
    badgeCritical: "KRITIKAL",
    badgeNormal: "Normal",
    language: "Lengguwahe",
    pushNotifications: "Mga Push Notipikasyon",
    enabled: "Nakabukas",
    disabled: "Nakasara",
    darkMode: "Madulom nga Theme",
    currentlyOn: "Nakabukas Subong",
    currentlyOff: "Nakasara Subong",
    accountSecurity: "Account kag Seguridad",
    accountSecurityDesc: "I-update ang profile ukon password",
    myProfile: "Akon Profile",
    householdList: "Listahan sang Panimalay",
    emergencyHotlines: "Mga Emergency Hotline",
    newsUpdates: "Balita kag Updates",
    emergencyTips: "Mga Emergency Tips",
    navHome: "Balay",
    navReport: "Mag-report",
    navDispatch: "Dispatch",
    navStatus: "Status",
    navVerify: "I-verify",
    navTeammates: "Mga Kaupod",
    navMap: "Mapa",
    navMore: "Dugang pa",
    searchHotlines: "Pangitaa ang mga hotline paagi sa ngalan, barangay, o numero...",
    recentlyCalled: "Bag-o Lang Gintawgan"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en'); // 'en' or 'hil'

  const toggleLanguage = () => {
    setLang(prev => prev === 'en' ? 'hil' : 'en');
  };

  const t = (key) => {
    return dictionary[lang][key] || dictionary['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
